version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: ai_phishing_backend:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./models:/app/models:rw
      - ./backend:/app/backend:ro

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=

volumes:
  mongo_data:
